[project]
name = "mcp-server-news"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agentops>=0.4.21",
    "crewai[mistral]>=1.4.1",
    "mcp[cli]>=1.21.1",
]
